### ISSUE TITLE
SIMBLInstaller - Opee Removal

### ISSUE THREAD

**Issue by alexzielenski** [w0lfschild/SIMBLPlugins#1]
The way you are removing Opee, just deleting the framework, is very unsafe and will cause the system to boot loop after the first reboot upon running it.

**Comment by w0lfschild** [comment]
Well I guess I'll take that part out then. Does opee conflict with SIMBL?

**Comment by justin0a0** [comment]
As far as I know it doesn't conflict in any way. It even loads (most) SIMBL bundles too
